cmake_minimum_required(VERSION 3.20)

add_library(${CONTROLLER_SUBPROGRAM_LIB_NAME} STATIC "controller_subprogram.cpp")
target_link_libraries(${CONTROLLER_SUBPROGRAM_LIB_NAME}
    PRIVATE ${CORE_LIB_NAME}
    PRIVATE ${HEADERS_ENGINE_LIB_NAME}
    PRIVATE ${MODEL_SUBPROGRAM_LIB_NAME}
    PRIVATE ${VIEW_SUBPROGRAM_LIB_NAME})
